[project]
name = "ckanext-csvinvite"
version = "0.0.1"
description = "**ckanext-csvinvite** is a CKAN plugin that enables organization administrators to bulk invite users by uploading a CSV file containing email addresses (and optional roles). It integrates with the existing invite and pending membership workflow, creating pending organization memberships that are automatically activated when users log in or accept their invitation, while providing proper permission checks and a detailed import report."
readme = "README.md"
authors = [
    {name = "Apostolos Vadrachanis", email = "apostolosvadrachanis@gmail.com"}
]
license = {text = "AGPL"}
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

keywords = [ "CKAN", ]
dependencies = []

[project.urls]
Homepage = "https://github.com/apostolosvadrachanis/ckanext-csvinvite"

[project.entry-points."ckan.plugins"]
csvinvite = "ckanext.csvinvite.plugin:CsvinvitePlugin"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
        "ignore::sqlalchemy.exc.SADeprecationWarning",
        "ignore::sqlalchemy.exc.SAWarning",
        "ignore::DeprecationWarning",
]
addopts = "--ckan-ini test.ini"
